branch-defaults:
  default:
    environment: asp-app-dev
global:
  application_name: asp-app
  default_ec2_keyname: docker-container
  default_platform: Docker 1.6.0
  default_region: ap-southeast-2
  profile: eb-cli
  sc: null
